-- Owner-approved Phase 1 baseline, 5 October 2026. No user accounts are created.
INSERT INTO airmech.permissions (code, description) VALUES
  ('profile.read', 'Authorized profile read action; server record policy required'),
  ('user.read', 'Authorized user read action; server record policy required'),
  ('user.create', 'Authorized user create action; server record policy required'),
  ('user.update', 'Authorized user update action; server record policy required'),
  ('user.disable', 'Authorized user disable action; server record policy required'),
  ('admin.users', 'Authorized admin users action; server record policy required'),
  ('admin.roles', 'Authorized admin roles action; server record policy required'),
  ('role.read', 'Authorized role read action; server record policy required'),
  ('permission.read', 'Authorized permission read action; server record policy required'),
  ('audit.read', 'Authorized audit read action; server record policy required'),
  ('settings.manage', 'Authorized settings manage action; server record policy required'),
  ('customer.read', 'Authorized customer read action; server record policy required'),
  ('customer.write', 'Authorized customer write action; server record policy required'),
  ('contact.read', 'Authorized contact read action; server record policy required'),
  ('contact.write', 'Authorized contact write action; server record policy required'),
  ('site.read', 'Authorized site read action; server record policy required'),
  ('site.write', 'Authorized site write action; server record policy required'),
  ('enquiry.read', 'Authorized enquiry read action; server record policy required'),
  ('enquiry.write', 'Authorized enquiry write action; server record policy required'),
  ('quotation.read', 'Authorized quotation read action; server record policy required'),
  ('quotation.create', 'Authorized quotation create action; server record policy required'),
  ('quotation.approve', 'Authorized quotation approve action; server record policy required'),
  ('project.read', 'Authorized project read action; server record policy required'),
  ('project.write', 'Authorized project write action; server record policy required'),
  ('asset.read', 'Authorized asset read action; server record policy required'),
  ('asset.write', 'Authorized asset write action; server record policy required'),
  ('warranty.read', 'Authorized warranty read action; server record policy required'),
  ('warranty.override', 'Authorized warranty override action; server record policy required'),
  ('complaint.read', 'Authorized complaint read action; server record policy required'),
  ('complaint.create', 'Authorized complaint create action; server record policy required'),
  ('complaint.assign', 'Authorized complaint assign action; server record policy required'),
  ('complaint.resolve', 'Authorized complaint resolve action; server record policy required'),
  ('complaint.submit_resolution', 'Authorized complaint submit_resolution action; server record policy required'),
  ('complaint.close', 'Authorized complaint close action; server record policy required'),
  ('complaint.reopen', 'Authorized complaint reopen action; server record policy required'),
  ('schedule.read', 'Authorized schedule read action; server record policy required'),
  ('schedule.assign', 'Authorized schedule assign action; server record policy required'),
  ('workorder.read', 'Authorized workorder read action; server record policy required'),
  ('workorder.write', 'Authorized workorder write action; server record policy required'),
  ('workorder.update_own', 'Authorized workorder update_own action; server record policy required'),
  ('workorder.parts', 'Authorized workorder parts action; server record policy required'),
  ('service_report.read', 'Authorized service_report read action; server record policy required'),
  ('service_report.write_own', 'Authorized service_report write_own action; server record policy required'),
  ('service_report.write', 'Authorized service_report write action; server record policy required'),
  ('amc.read', 'Authorized amc read action; server record policy required'),
  ('amc.write', 'Authorized amc write action; server record policy required'),
  ('pm.read', 'Authorized pm read action; server record policy required'),
  ('pm.write', 'Authorized pm write action; server record policy required'),
  ('document.read', 'Authorized document read action; server record policy required'),
  ('document.write', 'Authorized document write action; server record policy required'),
  ('document.field_read', 'Authorized document field.read action; server record policy required'),
  ('document.field_write', 'Authorized document field.write action; server record policy required'),
  ('report.read', 'Authorized report read action; server record policy required'),
  ('report.export', 'Authorized report export action; server record policy required'),
  ('dashboard.read', 'Authorized dashboard read action; server record policy required'),
  ('notification.read', 'Authorized notification read action; server record policy required')
ON CONFLICT (code) DO NOTHING;
INSERT INTO airmech.role_permissions (role_code, permission_code) VALUES
  ('super_admin', 'profile.read'),
  ('super_admin', 'user.read'),
  ('super_admin', 'user.create'),
  ('super_admin', 'user.update'),
  ('super_admin', 'user.disable'),
  ('super_admin', 'admin.users'),
  ('super_admin', 'admin.roles'),
  ('super_admin', 'role.read'),
  ('super_admin', 'permission.read'),
  ('super_admin', 'audit.read'),
  ('super_admin', 'settings.manage'),
  ('super_admin', 'customer.read'),
  ('super_admin', 'customer.write'),
  ('super_admin', 'contact.read'),
  ('super_admin', 'contact.write'),
  ('super_admin', 'site.read'),
  ('super_admin', 'site.write'),
  ('super_admin', 'enquiry.read'),
  ('super_admin', 'enquiry.write'),
  ('super_admin', 'quotation.read'),
  ('super_admin', 'quotation.create'),
  ('super_admin', 'quotation.approve'),
  ('super_admin', 'project.read'),
  ('super_admin', 'project.write'),
  ('super_admin', 'asset.read'),
  ('super_admin', 'asset.write'),
  ('super_admin', 'warranty.read'),
  ('super_admin', 'warranty.override'),
  ('super_admin', 'complaint.read'),
  ('super_admin', 'complaint.create'),
  ('super_admin', 'complaint.assign'),
  ('super_admin', 'complaint.resolve'),
  ('super_admin', 'complaint.submit_resolution'),
  ('super_admin', 'complaint.close'),
  ('super_admin', 'complaint.reopen'),
  ('super_admin', 'schedule.read'),
  ('super_admin', 'schedule.assign'),
  ('super_admin', 'workorder.read'),
  ('super_admin', 'workorder.write'),
  ('super_admin', 'workorder.update_own'),
  ('super_admin', 'workorder.parts'),
  ('super_admin', 'service_report.read'),
  ('super_admin', 'service_report.write_own'),
  ('super_admin', 'service_report.write'),
  ('super_admin', 'amc.read'),
  ('super_admin', 'amc.write'),
  ('super_admin', 'pm.read'),
  ('super_admin', 'pm.write'),
  ('super_admin', 'document.read'),
  ('super_admin', 'document.write'),
  ('super_admin', 'document.field_read'),
  ('super_admin', 'document.field_write'),
  ('super_admin', 'report.read'),
  ('super_admin', 'report.export'),
  ('super_admin', 'dashboard.read'),
  ('super_admin', 'notification.read'),
  ('management', 'profile.read'),
  ('management', 'customer.read'),
  ('management', 'customer.write'),
  ('management', 'contact.read'),
  ('management', 'contact.write'),
  ('management', 'site.read'),
  ('management', 'site.write'),
  ('management', 'enquiry.read'),
  ('management', 'enquiry.write'),
  ('management', 'quotation.read'),
  ('management', 'quotation.create'),
  ('management', 'quotation.approve'),
  ('management', 'project.read'),
  ('management', 'project.write'),
  ('management', 'asset.read'),
  ('management', 'asset.write'),
  ('management', 'warranty.read'),
  ('management', 'warranty.override'),
  ('management', 'complaint.read'),
  ('management', 'complaint.create'),
  ('management', 'complaint.assign'),
  ('management', 'complaint.resolve'),
  ('management', 'complaint.submit_resolution'),
  ('management', 'complaint.close'),
  ('management', 'complaint.reopen'),
  ('management', 'schedule.read'),
  ('management', 'schedule.assign'),
  ('management', 'workorder.read'),
  ('management', 'workorder.write'),
  ('management', 'workorder.update_own'),
  ('management', 'workorder.parts'),
  ('management', 'service_report.read'),
  ('management', 'service_report.write_own'),
  ('management', 'service_report.write'),
  ('management', 'amc.read'),
  ('management', 'amc.write'),
  ('management', 'pm.read'),
  ('management', 'pm.write'),
  ('management', 'document.read'),
  ('management', 'document.write'),
  ('management', 'document.field_read'),
  ('management', 'document.field_write'),
  ('management', 'report.read'),
  ('management', 'report.export'),
  ('management', 'dashboard.read'),
  ('management', 'notification.read'),
  ('management', 'user.read'),
  ('management', 'role.read'),
  ('management', 'permission.read'),
  ('management', 'audit.read'),
  ('sales_admin', 'profile.read'),
  ('sales_admin', 'dashboard.read'),
  ('sales_admin', 'notification.read'),
  ('sales_admin', 'customer.read'),
  ('sales_admin', 'customer.write'),
  ('sales_admin', 'contact.read'),
  ('sales_admin', 'contact.write'),
  ('sales_admin', 'site.read'),
  ('sales_admin', 'site.write'),
  ('sales_admin', 'enquiry.read'),
  ('sales_admin', 'enquiry.write'),
  ('sales_admin', 'quotation.read'),
  ('sales_admin', 'quotation.create'),
  ('sales_admin', 'project.read'),
  ('sales_admin', 'asset.read'),
  ('sales_admin', 'warranty.read'),
  ('sales_admin', 'complaint.read'),
  ('sales_admin', 'complaint.create'),
  ('sales_admin', 'workorder.read'),
  ('sales_admin', 'service_report.read'),
  ('sales_admin', 'amc.read'),
  ('sales_admin', 'pm.read'),
  ('sales_admin', 'document.read'),
  ('sales_admin', 'document.write'),
  ('sales_admin', 'report.read'),
  ('sales_admin', 'report.export'),
  ('service_manager', 'profile.read'),
  ('service_manager', 'dashboard.read'),
  ('service_manager', 'notification.read'),
  ('service_manager', 'customer.read'),
  ('service_manager', 'customer.write'),
  ('service_manager', 'contact.read'),
  ('service_manager', 'contact.write'),
  ('service_manager', 'site.read'),
  ('service_manager', 'site.write'),
  ('service_manager', 'enquiry.read'),
  ('service_manager', 'quotation.read'),
  ('service_manager', 'project.read'),
  ('service_manager', 'asset.read'),
  ('service_manager', 'asset.write'),
  ('service_manager', 'warranty.read'),
  ('service_manager', 'warranty.override'),
  ('service_manager', 'complaint.read'),
  ('service_manager', 'complaint.create'),
  ('service_manager', 'complaint.assign'),
  ('service_manager', 'complaint.resolve'),
  ('service_manager', 'complaint.close'),
  ('service_manager', 'complaint.reopen'),
  ('service_manager', 'schedule.read'),
  ('service_manager', 'schedule.assign'),
  ('service_manager', 'workorder.read'),
  ('service_manager', 'workorder.write'),
  ('service_manager', 'service_report.read'),
  ('service_manager', 'service_report.write'),
  ('service_manager', 'amc.read'),
  ('service_manager', 'amc.write'),
  ('service_manager', 'pm.read'),
  ('service_manager', 'pm.write'),
  ('service_manager', 'document.read'),
  ('service_manager', 'document.write'),
  ('service_manager', 'report.read'),
  ('service_manager', 'report.export'),
  ('engineer', 'profile.read'),
  ('engineer', 'dashboard.read'),
  ('engineer', 'notification.read'),
  ('engineer', 'customer.read'),
  ('engineer', 'site.read'),
  ('engineer', 'contact.read'),
  ('engineer', 'asset.read'),
  ('engineer', 'warranty.read'),
  ('engineer', 'complaint.read'),
  ('engineer', 'complaint.create'),
  ('engineer', 'complaint.submit_resolution'),
  ('engineer', 'schedule.read'),
  ('engineer', 'workorder.read'),
  ('engineer', 'workorder.update_own'),
  ('engineer', 'workorder.parts'),
  ('engineer', 'service_report.read'),
  ('engineer', 'service_report.write_own'),
  ('engineer', 'amc.read'),
  ('engineer', 'pm.read'),
  ('engineer', 'document.field_read'),
  ('engineer', 'document.field_write'),
  ('engineer', 'report.read'),
  ('project_manager', 'profile.read'),
  ('project_manager', 'dashboard.read'),
  ('project_manager', 'notification.read'),
  ('project_manager', 'customer.read'),
  ('project_manager', 'customer.write'),
  ('project_manager', 'contact.read'),
  ('project_manager', 'contact.write'),
  ('project_manager', 'site.read'),
  ('project_manager', 'site.write'),
  ('project_manager', 'enquiry.read'),
  ('project_manager', 'quotation.read'),
  ('project_manager', 'project.read'),
  ('project_manager', 'project.write'),
  ('project_manager', 'asset.read'),
  ('project_manager', 'asset.write'),
  ('project_manager', 'warranty.read'),
  ('project_manager', 'complaint.read'),
  ('project_manager', 'complaint.create'),
  ('project_manager', 'schedule.read'),
  ('project_manager', 'schedule.assign'),
  ('project_manager', 'workorder.read'),
  ('project_manager', 'workorder.write'),
  ('project_manager', 'service_report.read'),
  ('project_manager', 'amc.read'),
  ('project_manager', 'pm.read'),
  ('project_manager', 'document.read'),
  ('project_manager', 'document.write'),
  ('project_manager', 'report.read'),
  ('project_manager', 'report.export'),
  ('accounts', 'profile.read'),
  ('accounts', 'dashboard.read'),
  ('accounts', 'notification.read'),
  ('accounts', 'customer.read'),
  ('accounts', 'contact.read'),
  ('accounts', 'site.read'),
  ('accounts', 'enquiry.read'),
  ('accounts', 'quotation.read'),
  ('accounts', 'project.read'),
  ('accounts', 'asset.read'),
  ('accounts', 'warranty.read'),
  ('accounts', 'complaint.read'),
  ('accounts', 'workorder.read'),
  ('accounts', 'service_report.read'),
  ('accounts', 'amc.read'),
  ('accounts', 'pm.read'),
  ('accounts', 'document.read'),
  ('accounts', 'report.read'),
  ('accounts', 'report.export'),
  ('store', 'profile.read'),
  ('store', 'dashboard.read'),
  ('store', 'notification.read'),
  ('store', 'customer.read'),
  ('store', 'contact.read'),
  ('store', 'site.read'),
  ('store', 'project.read'),
  ('store', 'asset.read'),
  ('store', 'warranty.read'),
  ('store', 'complaint.read'),
  ('store', 'workorder.read'),
  ('store', 'workorder.parts'),
  ('store', 'amc.read'),
  ('store', 'pm.read'),
  ('store', 'document.read'),
  ('store', 'report.read'),
  ('store', 'report.export')
ON CONFLICT DO NOTHING;

ALTER TABLE airmech.users ADD COLUMN auth_locked_until timestamptz;
ALTER TABLE airmech.audit_events ADD COLUMN details jsonb NOT NULL DEFAULT '{}'::jsonb
  CHECK (jsonb_typeof(details)='object' AND octet_length(details::text)<=16384);
CREATE TABLE airmech.auth_sessions (
  token_hash text PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  user_id uuid NOT NULL REFERENCES airmech.users(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('login', 'recovery', 'invite')),
  provider_access_ciphertext text,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL CHECK (expires_at > created_at),
  CHECK ((kind = 'login' AND provider_access_ciphertext IS NULL) OR (kind IN ('recovery', 'invite') AND provider_access_ciphertext IS NOT NULL))
);
CREATE INDEX auth_sessions_user ON airmech.auth_sessions (user_id);
CREATE INDEX auth_sessions_expiry ON airmech.auth_sessions (expires_at);
CREATE TABLE airmech.auth_recovery_requests (
  state_hash text PRIMARY KEY CHECK (state_hash ~ '^[0-9a-f]{64}$'),
  verifier_ciphertext text NOT NULL,
  expires_at timestamptz NOT NULL
);
CREATE INDEX auth_recovery_expiry ON airmech.auth_recovery_requests (expires_at);
CREATE TABLE airmech.auth_rate_limits (
  key_hash text PRIMARY KEY CHECK (key_hash ~ '^[0-9a-f]{64}$'),
  attempts integer NOT NULL CHECK (attempts > 0),
  expires_at timestamptz NOT NULL
);
CREATE INDEX auth_rate_expiry ON airmech.auth_rate_limits (expires_at);
CREATE TABLE airmech.auth_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL CHECK (kind IN ('recovery','invite')),
  payload_ciphertext text NOT NULL CHECK (length(payload_ciphertext)<=24000),
  user_id uuid REFERENCES airmech.users(id) ON DELETE RESTRICT,
  recovery_state_hash text REFERENCES airmech.auth_recovery_requests(state_hash) ON DELETE CASCADE,
  actor_id uuid REFERENCES airmech.users(id) ON DELETE RESTRICT,
  request_id text NOT NULL CHECK (length(request_id) BETWEEN 1 AND 128),
  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','sent','failed','cancelled','expired')),
  created_at timestamptz NOT NULL DEFAULT now(),
  lease_id uuid,
  lease_until timestamptz,
  expires_at timestamptz NOT NULL,
  CHECK ((kind='invite' AND user_id IS NOT NULL AND recovery_state_hash IS NULL) OR (kind='recovery' AND user_id IS NULL AND recovery_state_hash IS NOT NULL))
);
CREATE INDEX auth_messages_expiry ON airmech.auth_messages(expires_at);
CREATE INDEX auth_messages_user_delivery ON airmech.auth_messages(user_id,created_at DESC,id);
ALTER TABLE airmech.auth_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE airmech.auth_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE airmech.auth_recovery_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE airmech.auth_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA airmech FROM PUBLIC;
